### ISSUE TITLE
【已解决】imu_raw_data 数据异常

### ISSUE THREAD

**Issue by mz8023yt** [Slamtec/aurora_ros#2]
Aurora 设备水平放置，角加速度的值异常

```
---
header: 
  seq: 301440
  stamp: 
    secs: 1747622965
    nsecs: 819155945
  frame_id: "imu_link"
orientation: 
  x: -0.7779680188495378
  y: 0.15098026637532816
  z: 0.18376044614515222
  w: 0.581552077844362
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.30517578125
  y: 0.48828125
  z: 1.89208984375
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.97021484375
  y: -0.068115234375
  z: -0.012451171875
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
---
header: 
  seq: 301441
  stamp: 
    secs: 1747622965
    nsecs: 819174676
  frame_id: "imu_link"
orientation: 
  x: -0.7779681265670612
  y: 0.15099701189543122
  z: 0.18376347177141134
  w: 0.5815466300193872
orientation_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
angular_velocity: 
  x: -0.18310546875
  y: 0.8544921875
  z: 1.77001953125
angular_velocity_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
linear_acceleration: 
  x: 0.9163818359375
  y: -0.000244140625
  z: 0.0421142578125
linear_acceleration_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

我看代码，这个值是从 sdk 直接获取到的，这个值有问题

```
void ServerImuRawDataWorker::doPerform()
    {
        auto auroraSDK = rosSdkServer()->safeGetAuroraSdk();
        std::vector<slamtec_aurora_sdk_imu_data_t> imuData;
        if (auroraSDK->dataProvider.peekIMUData(imuData))
        {
            for (auto &imu : imuData)
            {
                lastTimestamp_ = imu.timestamp_ns;
                const auto &srvParams = serverParams();
                sensor_msgs::Imu imuRawDataRos;
                imuRawDataRos.linear_acceleration.x = imu.acc[0];
                imuRawDataRos.linear_acceleration.y = imu.acc[1];
                imuRawDataRos.linear_acceleration.z = imu.acc[2];
                imuRawDataRos.angular_velocity.x = imu.gyro[0];
                imuRawDataRos.angular_velocity.y = imu.gyro[1];
                imuRawDataRos.angular_velocity.z = imu.gyro[2];
                imuRawDataRos.header.stamp = ros::Time::now();
                imuRawDataRos.header.frame_id = srvParams.imu_frame;
                pubImuRawData_.publish(imuRawDataRos);
            }
        }
    }
```
